### ISSUE TITLE
Address length -= 8; without size checks

### ISSUE THREAD

**Issue by asveikau** [takakia/lovok#60]
As mentioned in the call, there are scattered additions/subtractions in box parsing that assume the length is big enough.  This is a red flag!

We discussed hypothetical solutions like:

* Add size check and throw exception?
* Helper method that does size check?
* Maybe have the caller not include the header when parsing the box?  To side-step the need for these additions/subtractions

**Comment by smiller1212** [comment]
Resolved by #69
